# Generated by Django 2.2.20 on 2021-08-10 16:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('account_id', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Account ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('mid_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('national_id', models.ImageField(upload_to='', verbose_name='National ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile Number')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('date_of_investment', models.DateField(verbose_name='Date of Investment')),
                ('vod_cash_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Vodafone Cash Mobile Number')),
                ('last_contacted', models.DateTimeField(blank=True, null=True, verbose_name='Last Contact')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('min_value', models.PositiveSmallIntegerField(verbose_name='Minimum Value')),
                ('max_value', models.PositiveSmallIntegerField(verbose_name='Maximum Value')),
                ('bundle_per', models.FloatField(verbose_name='Bundle Percentage %')),
                ('referral_per', models.FloatField(verbose_name='Referral Percentage %')),
                ('referral_breakeven_lvl', models.FloatField(verbose_name='Referral Breakeven Level %')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=11, verbose_name='Type')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('amount_EGP', models.FloatField(blank=True, null=True, verbose_name='Amount EGP')),
                ('deliverd_rate', models.FloatField(verbose_name='USD/EGP rate')),
                ('real_rate', models.FloatField(verbose_name='USD/EGP real rate')),
                ('amount_USD', models.FloatField(blank=True, null=True, verbose_name='Amount USD')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.Account', verbose_name='Account')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.TransactionType', verbose_name='Transaction Type')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('main_wallet_EGP', models.FloatField(default=0, verbose_name='Main Wallet (EGP)')),
                ('main_wallet_USD', models.FloatField(default=0, verbose_name='Main Wallet (USD)')),
                ('balance', models.FloatField(default=0, verbose_name='Current Balance')),
                ('trading_result_last_week', models.FloatField(blank=True, editable=False, null=True, verbose_name='Trading Result Last Week')),
                ('total_achievement', models.FloatField(default=0, editable=False, verbose_name='Total Achievement')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forex.Account', verbose_name='Account')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.AccountType', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='account',
            name='bundle',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='forex.Bundle', verbose_name='Bundle'),
        ),
    ]
