# Generated by Django 3.2.5 on 2021-07-26 20:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('account_id', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Account ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('mid_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile Number')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('date_of_investment', models.DateField(verbose_name='Date of Investment')),
                ('vod_cash_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Vodafone Cash Mobile Number')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Contact')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('min_value', models.PositiveSmallIntegerField(verbose_name='Minimum Value')),
                ('max_value', models.PositiveSmallIntegerField(verbose_name='Maximum Value')),
                ('bundle_per', models.FloatField(verbose_name='Bundle Percentage %')),
                ('referral_per', models.FloatField(verbose_name='Referral Percentage %')),
                ('referral_breakeven_lvl', models.FloatField(verbose_name='Referral Breakeven Level %')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('share', models.FloatField(default=0, editable=False, verbose_name='Share %')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.account', verbose_name='Account')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TotalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('total_USD', models.FloatField(verbose_name='Total Trading Amount USD')),
                ('total_EGP', models.FloatField(verbose_name='Total Trading Amount EGP')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('amount_EGP', models.FloatField(blank=True, null=True, verbose_name='Amount EGP')),
                ('rate', models.FloatField(verbose_name='USD/EGP rate')),
                ('amount_USD', models.FloatField(blank=True, null=True, verbose_name='Amount USD')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.account', verbose_name='Account')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.transactiontype', verbose_name='Transaction Type')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stockholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('profit_share_per', models.FloatField(verbose_name='Profit Share Percentage %')),
                ('PL_balance', models.FloatField(default=0, verbose_name='PL Balance in USD')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.account', verbose_name='Stockholder Account')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharePL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('share_cut', models.FloatField(editable=False, verbose_name='Total Share Cut USD')),
                ('bundle_cut', models.FloatField(editable=False, verbose_name='Bundle Cut USD')),
                ('account_cut', models.FloatField(editable=False, verbose_name='Account Cut USD')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.share', verbose_name='Share')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('referral_bonus', models.FloatField(editable=False, verbose_name='Referral Bonus')),
                ('bonus_trans', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forex.transaction', verbose_name='Bonus Transaction')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='forex.account', verbose_name='Customer')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='forex.account', verbose_name='Referred By')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('amount', models.FloatField(verbose_name='Amount USD')),
                ('finance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.financetype', verbose_name='Finance Type')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('main_wallet_EGP', models.FloatField(default=0, verbose_name='Main Wallet EGP')),
                ('main_wallet_USD', models.FloatField(default=0, verbose_name='Main Wallet USD')),
                ('balance', models.FloatField(default=0, verbose_name='Balance USD')),
                ('trading_result_last_week', models.FloatField(blank=True, editable=False, null=True, verbose_name='Trading Result Last Week')),
                ('total_achievement', models.FloatField(default=0, editable=False, verbose_name='Total Achievement')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forex.account', verbose_name='Account')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.accounttype', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='account',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.bundle', verbose_name='Bundle'),
        ),
    ]
