# Generated by Django 3.2.5 on 2021-07-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_contact_date',
            new_name='last_contacted',
        ),
        migrations.AlterField(
            model_name='account',
            name='bundle',
            field=models.ForeignKey(blank=True, editable=False, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='forex.bundle', verbose_name='Bundle'),
        ),
    ]
