# Generated by Django 2.2.20 on 2021-08-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forex.Balance', verbose_name='Balance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deliverd_rate',
            field=models.FloatField(verbose_name='USD/EGP Delivered Rate'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='real_rate',
            field=models.FloatField(verbose_name='USD/EGP Real Rate'),
        ),
    ]
