# Generated by Django 2.2.20 on 2021-08-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='national_id',
            field=models.ImageField(blank=True, null=True, upload_to='nationalIDs', verbose_name='National ID'),
        ),
    ]
