# Generated by Django 2.2.20 on 2021-08-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_auto_20210810_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='active',
        ),
    ]
