# Generated by Django 2.2.20 on 2021-08-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0003_remove_transaction_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='main_wallet_EGP',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='main_wallet_USD',
        ),
        migrations.AddField(
            model_name='balance',
            name='main_wallet',
            field=models.FloatField(default=0, verbose_name='Main Wallet'),
        ),
    ]
