# Generated by Django 2.2.20 on 2021-08-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0004_auto_20210810_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('total', models.FloatField(verbose_name='Total Trading Amount')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='PL',
            field=models.FloatField(default=0, verbose_name='Profit/Loss'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='trading_result_last_week',
            field=models.FloatField(default=0, editable=False, verbose_name='Trading Result Last Week'),
        ),
    ]
