# Generated by Django 2.2.20 on 2021-08-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0005_auto_20210812_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalasset',
            name='PLs',
            field=models.FloatField(default=0, editable=False, verbose_name='Last Week P/L'),
        ),
        migrations.AddField(
            model_name='totalasset',
            name='deposits',
            field=models.FloatField(default=0, editable=False, verbose_name='Total Deposits'),
        ),
        migrations.AddField(
            model_name='totalasset',
            name='withdrawals',
            field=models.FloatField(default=0, editable=False, verbose_name='Total Withdrawals'),
        ),
    ]
