# Generated by Django 2.2.20 on 2021-08-14 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0007_auto_20210812_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='national_id',
            field=models.ImageField(upload_to='media/nationalIDs', verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_EGP',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount (EGP)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_USD',
            field=models.FloatField(blank=True, null=True, verbose_name=' Amount (USD)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deliverd_rate',
            field=models.FloatField(help_text='EGP/USD', verbose_name='Delivered Rate'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='real_rate',
            field=models.FloatField(help_text='EGP/USD', verbose_name='Real Rate'),
        ),
    ]
