# Generated by Django 2.2.20 on 2021-08-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0008_auto_20210814_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=10, verbose_name='Transaction Type'),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.TransactionChannel', verbose_name='Transaction Type'),
            preserve_default=False,
        ),
    ]
