# Generated by Django 2.2.20 on 2021-08-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0009_auto_20210814_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='national_id',
            field=models.ImageField(upload_to='nationalIDs', verbose_name='National ID'),
        ),
    ]
