# Generated by Django 2.2.20 on 2021-08-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0010_auto_20210814_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='share',
            field=models.FloatField(blank=True, null=True, verbose_name='Share Percentage'),
        ),
    ]
