# Generated by Django 2.2.20 on 2021-08-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0011_balance_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='share',
            field=models.FloatField(default=0, verbose_name='Share Percentage'),
        ),
        migrations.CreateModel(
            name='SharePL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('share_cut', models.FloatField(editable=False, verbose_name='Total Share Cut USD')),
                ('bundle_cut', models.FloatField(editable=False, verbose_name='Bundle Cut USD')),
                ('account_cut', models.FloatField(editable=False, verbose_name='Account Cut USD')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.Balance', verbose_name='Share')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
